resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/26.yaml

packages:
  - .

extra-deps:
  - gloss-1.13.2.1
  - hmidi-0.2.3.1
  - hosc-0.18.1
  - hsc3-0.18
  - tidal-1.6.1

  - cairo-0.13.8.1
  - gio-0.13.8.1
  - glib-0.13.8.1
  - gtk-0.15.5
  - gtk2hs-buildtools-0.13.8.0
  - pango-0.13.8.1

  - stm-2.5.0.0
  - Win32-2.8.5.0

  - Cabal-3.2.1.0
  - directory-1.3.6.1
  - process-1.6.10.0
  - time-1.10

  # - gi-atk-2.0.22
  # - gi-cairo-1.0.24
  # - gi-gdk-4.0.2
  # - gi-gdkpixbuf-2.0.24
  # - gi-gio-2.0.27
  # - gi-glib-2.0.24
  # - gi-gobject-2.0.25
  # - gi-graphene-1.0.2
  # - gi-gsk-4.0.2
  # - gi-gtk-4.0.3
  # - gi-harfbuzz-0.0.3
  # - gi-pango-1.0.23
  # - haskell-gi-0.24.7
  # - haskell-gi-base-0.24.5
